apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-app/statefulset.yaml
  - postgres-app/service.yaml
  - postgres-keycloak/statefulset.yaml
  - postgres-keycloak/service.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
