apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go
  namespace: coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-go
  template:
    metadata:
      labels:
        app: backend-go
    spec:
      containers:
        - name: backend-go
          image: ghcr.io/mastilovic/coffeeshop-backend-go:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-go-config
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
